### ISSUE TITLE
Failing to import dumps

### ISSUE THREAD

**Issue by mhanne** [mhanne/block_browser#15]
A user reported problems when importing a dump.

```
I ran into an error when trying to load it in both 9.3 and 9.4 postgres. The import runs fine for maybe 5 minutes, then fails on error
 ERROR: missing data for column “type”
```

Could it be an issue with postgres > 9.1?

**Comment by CzechJiri** [comment]
just to add, the error occurs when running

```
 echo "create database bitcoin" | psql
 curl http://dumps.webbtc.com/bitcoin/bitcoin_yyyy-mm-dd.sql.gz | gunzip | psql bitcoin
```

I was digging a bit deeper, the issue is not in postgres import, but when wget retries during download interruption (I think wget send the notification about the error to the pipe). Running wget first, then the import fixes the issue

```
wget -t 99 http://dumps.webbtc.com/bitcoin/bitcoin_yyyy-mm-dd.sql.gz
zcat bitcoin_yyyy-mm-dd.sql.gz | psql bitcoin
```


the import works on postgres 9.3 (tested in standard docker postgres 9.3 image)

**Comment by mhanne** [comment]
Thanks for digging into it! I updated the README on http://dumps.webbtc.com.
